---
abstract: 'LaTeX CatSuit'
author:
  - 'Jerome Eteve <jeteve@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LaTeX-CatSuit
no_index:
  directory:
    - t
    - inc
requires:
  BSD::Resource: 0
  Class::Accessor: 0
  Cwd: 0
  Exception::Class: 0
  File::Slurp: 0
  File::Spec: 0
  IO::File: 0
  Test::Exception: 0
  Test::More: 0
version: 1.00_01
